// pages/Home/sections/Start/index.vue
<template>
  <section id="start">
    <div class="container start-container">
      <div class="start-left">
        <span class="start-badge">{{ $t('home-badge') }}</span>
        
        <h1 class="start-heading">
          {{ $t('home-header') }}
        </h1>
        
        <p class="start-description">
          {{ $t('home-description') }}
        </p>

        <div class="start-features">
          <div class="feature-item">
            <div class="feature-icon">
              <Icon name="mdi:currency-usd" />
            </div>
            <div class="feature-content">
              <span>{{ $t('home-feature-save-title') }}</span>
              <p>{{ $t('home-feature-save-desc') }}</p>
            </div>
          </div>
          
          <div class="feature-item">
            <div class="feature-icon">
              <Icon name="mdi:lightning-bolt" />
            </div>
            <div class="feature-content">
              <span>{{ $t('home-feature-fast-title') }}</span>
              <p>{{ $t('home-feature-fast-desc') }}</p>
            </div>
          </div>

          <div class="feature-item">
            <div class="feature-icon">
              <Icon name="mdi:shield-check" />
            </div>
            <div class="feature-content">
              <span>{{ $t('home-feature-secure-title') }}</span>
              <p>{{ $t('home-feature-secure-desc') }}</p>
            </div>
          </div>
        </div>

        <p class="start-note">
          {{ $t('home-note') }}
        </p>

        <div class="start-social-proof">
          <Icon name="mdi:rocket-launch-outline" />
          <span>{{ $t('home-social-proof') }}</span>
        </div>
      </div>

      <div class="start-right">
        <nuc-section-email-us />
      </div>
    </div>
  </section>
</template>

// pages/home/sections/start/index.tsx
'use client'

import type { JSX } from 'react'

import { AdIcon, NucSectionEmailUs, t } from 'nucleify'

import './_index.scss'

const startFeatureItems = [
  {
    icon: 'mdi:currency-usd' as const,
    titleKey: 'home-feature-save-title',
    descKey: 'home-feature-save-desc',
  },
  {
    icon: 'mdi:lightning-bolt' as const,
    titleKey: 'home-feature-fast-title',
    descKey: 'home-feature-fast-desc',
  },
  {
    icon: 'mdi:shield-check' as const,
    titleKey: 'home-feature-secure-title',
    descKey: 'home-feature-secure-desc',
  },
]

export function NucStart(): JSX.Element {
  return (
    <section id="start">
      <div className="container start-container">
        <div className="start-left">
          <span className="start-badge">{t('home-badge')}</span>

          <h1 className="start-heading">{t('home-header')}</h1>

          <p className="start-description">{t('home-description')}</p>

          <div className="start-features">
            {startFeatureItems.map((item) => (
              <div className="feature-item" key={item.titleKey}>
                <div className="feature-icon">
                  <AdIcon icon={item.icon} />
                </div>
                <div className="feature-content">
                  <span>{t(item.titleKey)}</span>
                  <p>{t(item.descKey)}</p>
                </div>
              </div>
            ))}
          </div>

          <p className="start-note">{t('home-note')}</p>

          <div className="start-social-proof">
            <AdIcon icon="mdi:rocket-launch-outline" />
            <span>{t('home-social-proof')}</span>
          </div>
        </div>

        <div className="start-right">
          <NucSectionEmailUs />
        </div>
      </div>
    </section>
  )
}
