// pages/company/process/index.tsx
'use client'

import type { JSX } from 'react'

import {
  NucProcessGuarantees,
  NucProcessStart,
  NucProcessSteps,
  NucSectionContact,
} from 'nucleify'

import './_index.scss'

export function NucProcessPage(): JSX.Element {
  return (
    <div className="process-container">
      <NucProcessStart />
      <NucProcessSteps />
      <NucProcessGuarantees />
      <NucSectionContact />
    </div>
  )
}

// pages/company/process/index.vue
<template>
  <div class="process-container">
    <nuc-process-start />
    <nuc-process-steps />
    <nuc-process-guarantees />
    <nuc-section-contact />
  </div>
</template>

<script setup lang="ts">
import {
  NucProcessStart,
  NucProcessSteps,
  NucProcessGuarantees,
  NucSectionContact,
} from 'nucleify'
</script>

<style lang="scss">
@import 'index';
</style>
