// pages/services/index.tsx
'use client'

import type { JSX } from 'react'

import {
  AdIcon,
  NucSectionContact,
  NucSectionFaq,
  NucShinyBadge,
  t,
} from 'nucleify'

import './_index.scss'

export function NucServicesPage(): JSX.Element {
  const services = [
    {
      icon: 'mdi:domain',
      title: t('service-main-bw-title'),
      desc: t('service-main-bw-desc'),
      url: '/en/services/business-websites',
    },
    {
      icon: 'mdi:cart-outline',
      title: t('service-main-ec-title'),
      desc: t('service-main-ec-desc'),
      url: '/en/services/ecommerce-stores',
    },
    {
      icon: 'mdi:lightning-bolt',
      title: t('service-main-lp-title'),
      desc: t('service-main-lp-desc'),
      url: '/en/services/landing-pages',
    },
    {
      icon: 'mdi:auto-fix',
      title: t('service-main-wr-title'),
      desc: t('service-main-wr-desc'),
      url: '/en/services/website-redesign',
    },
    {
      icon: 'mdi:puzzle-outline',
      title: t('service-main-cp-title'),
      desc: t('service-main-cp-desc'),
      url: '/en/services/custom-projects',
    },
  ]

  return (
    <div className="service-container">
      <section className="service-hero">
        <div className="service-hero-decoration service-hero-decoration-1">
          <AdIcon icon="mdi:hexagon-outline" />
        </div>
        <div className="service-hero-decoration service-hero-decoration-2">
          <AdIcon icon="mdi:triangle-outline" />
        </div>

        <div className="service-hero-content container">
          <NucShinyBadge
            icon="mdi:briefcase-outline"
            label={t('service-main-badge')}
          />
          <h1 className="service-hero-title">
            {t('service-main-title')}
            <span className="service-hero-title-highlight">
              {t('service-main-title-highlight')}
            </span>
          </h1>
          <p className="service-hero-subtitle">{t('service-main-subtitle')}</p>
        </div>
      </section>

      <section className="service-features">
        <div className="container">
          <div className="service-features-grid">
            {services.map((service) => (
              <a
                key={service.title}
                href={service.url}
                className="service-feature-card service-feature-card-link"
              >
                <div className="service-feature-card-icon">
                  <AdIcon icon={service.icon} />
                </div>
                <h3>{service.title}</h3>
                <p>{service.desc}</p>
                <span className="service-feature-card-arrow">
                  <AdIcon icon="mdi:arrow-right" />
                </span>
              </a>
            ))}
          </div>
        </div>
      </section>

      <NucSectionFaq site="home" />
      <NucSectionContact />
    </div>
  )
}

// pages/services/index.vue
<template>
  <div class="service-container">
    <section class="service-hero">
      <div class="service-hero-decoration service-hero-decoration-1">
        <Icon name="mdi:hexagon-outline" />
      </div>
      <div class="service-hero-decoration service-hero-decoration-2">
        <Icon name="mdi:triangle-outline" />
      </div>

      <div class="service-hero-content container">
        <nuc-shiny-badge
          icon="mdi:briefcase-outline"
          :label="$t('service-main-badge')"
        />

        <h1 class="service-hero-title">
          {{ $t('service-main-title') }}
          <span class="service-hero-title-highlight">
            {{ $t('service-main-title-highlight') }}
          </span>
        </h1>

        <p class="service-hero-subtitle">{{ $t('service-main-subtitle') }}</p>
      </div>
    </section>

    <section class="service-features">
      <div class="container">
        <div class="service-features-grid">
          <nuxt-link
            v-for="service in services"
            :key="service.title"
            :to="service.url"
            class="service-feature-card service-feature-card-link"
          >
            <div class="service-feature-card-icon">
              <Icon :name="service.icon" />
            </div>
            <h3>{{ service.title }}</h3>
            <p>{{ service.desc }}</p>
            <span class="service-feature-card-arrow">
              <Icon name="mdi:arrow-right" />
            </span>
          </nuxt-link>
        </div>
      </div>
    </section>

    <LazyNucSectionFaq site="home" />
    <LazyNucSectionContact />
  </div>
</template>

<script setup lang="ts">
import { defineAsyncComponent } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'

const { t } = useI18n()
const route = useRoute()
const lang = (route.params.lang as string) || 'en'

const services = [
  {
    icon: 'mdi:domain',
    title: t('service-main-bw-title'),
    desc: t('service-main-bw-desc'),
    url: `/${lang}/services/business-websites`,
  },
  {
    icon: 'mdi:cart-outline',
    title: t('service-main-ec-title'),
    desc: t('service-main-ec-desc'),
    url: `/${lang}/services/ecommerce-stores`,
  },
  {
    icon: 'mdi:lightning-bolt',
    title: t('service-main-lp-title'),
    desc: t('service-main-lp-desc'),
    url: `/${lang}/services/landing-pages`,
  },
  {
    icon: 'mdi:auto-fix',
    title: t('service-main-wr-title'),
    desc: t('service-main-wr-desc'),
    url: `/${lang}/services/website-redesign`,
  },
  {
    icon: 'mdi:puzzle-outline',
    title: t('service-main-cp-title'),
    desc: t('service-main-cp-desc'),
    url: `/${lang}/services/custom-projects`,
  },
]

const LazyNucSectionFaq = defineAsyncComponent(
  () => import('../../../nuc_sections/faq/index.vue')
)
const LazyNucSectionContact = defineAsyncComponent(
  () => import('../../../nuc_sections/contact/index.vue')
)
</script>

<style lang="scss">
@import 'index';
</style>
