// pages/dev/sections/dx/index.vue
<template>
  <section id="dev-dx" class="dev-dx">
    <div class="dev-dx-bg">
      <div class="dev-dx-orb dev-dx-orb-1" />
      <div class="dev-dx-orb dev-dx-orb-2" />
    </div>

    <div class="container">
      <div class="dev-dx-layout">
        <div class="dev-dx-nav">
          <button
            v-for="(item, i) in dxFeatures"
            :key="item.key"
            class="dev-dx-nav-item"
            :class="{ 'dev-dx-nav-item-active': activeIndex === i }"
            @click="activeIndex = i"
          >
            <div class="dev-dx-nav-icon"><Icon :name="item.icon" /></div>
            <div class="dev-dx-nav-text">
              <h3>{{ item.title }}</h3>
              <p>{{ item.desc }}</p>
            </div>
            <div class="dev-dx-nav-arrow">
              <Icon name="mdi:chevron-right" />
            </div>
          </button>
        </div>

        <div class="dev-dx-preview">
          <div class="dev-dx-preview-window">
            <div class="dev-dx-preview-bar">
              <span /><span /><span />
              <div class="dev-dx-preview-tab">
                {{ dxFeatures[activeIndex].file }}
              </div>
            </div>
            <div class="dev-dx-preview-body">
              <transition name="dev-dx-fade" mode="out-in">
                <div :key="activeIndex" class="dev-dx-code-wrap">
                  <div class="dev-dx-line-numbers">
                    <span v-for="n in lineCount" :key="n">{{ n }}</span>
                  </div>
                  <pre><code>{{ dxFeatures[activeIndex].code }}</code></pre>
                </div>
              </transition>
            </div>
            <div class="dev-dx-preview-status">
              <span>{{ dxFeatures[activeIndex].lang }}</span>
              <span>UTF-8</span>
              <span>Ln {{ lineCount }}, Col 1</span>
            </div>
          </div>
          <div class="dev-dx-preview-glow" />
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import { DX_FEATURE_DEFINITIONS } from 'nucleify'

const { t } = useI18n()
const activeIndex = ref(0)

const dxFeatures = computed(() =>
  DX_FEATURE_DEFINITIONS.map((item) => ({
    ...item,
    title: t(item.titleKey),
    desc: t(item.descKey),
  }))
)

const lineCount = computed(
  () => dxFeatures.value[activeIndex.value].code.split('\n').length
)
</script>

<style lang="scss">
@import 'index';
</style>

// pages/dev/sections/dx/index.tsx
'use client'

import type { JSX } from 'react'
import { useMemo, useState } from 'react'

import { AdIcon, DX_FEATURE_DEFINITIONS, t } from 'nucleify'

import './_index.scss'

export function NucDevDX(): JSX.Element {
  const [activeIndex, setActiveIndex] = useState(0)

  const dxFeatures = useMemo(
    () =>
      DX_FEATURE_DEFINITIONS.map((item) => ({
        ...item,
        title: t(item.titleKey),
        desc: t(item.descKey),
      })),
    []
  )

  const lineCount = useMemo(
    () => dxFeatures[activeIndex].code.split('\n').length,
    [activeIndex, dxFeatures]
  )
  const activeFeature = dxFeatures[activeIndex]

  return (
    <section id="dev-dx" className="dev-dx">
      <div className="dev-dx-bg">
        <div className="dev-dx-orb dev-dx-orb-1" />
        <div className="dev-dx-orb dev-dx-orb-2" />
      </div>

      <div className="container">
        <div className="dev-dx-layout">
          <div className="dev-dx-nav">
            {dxFeatures.map((item, index) => (
              <button
                key={item.key}
                className={`dev-dx-nav-item ${
                  activeIndex === index ? 'dev-dx-nav-item-active' : ''
                }`}
                onClick={() => setActiveIndex(index)}
                type="button"
              >
                <div className="dev-dx-nav-icon">
                  <AdIcon icon={item.icon} />
                </div>
                <div className="dev-dx-nav-text">
                  <h3>{item.title}</h3>
                  <p>{item.desc}</p>
                </div>
                <div className="dev-dx-nav-arrow">
                  <AdIcon icon="mdi:chevron-right" />
                </div>
              </button>
            ))}
          </div>

          <div className="dev-dx-preview">
            <div className="dev-dx-preview-window">
              <div className="dev-dx-preview-bar">
                <span />
                <span />
                <span />
                <div className="dev-dx-preview-tab">{activeFeature.file}</div>
              </div>
              <div className="dev-dx-preview-body">
                <div className="dev-dx-code-wrap">
                  <div className="dev-dx-line-numbers">
                    {Array.from({ length: lineCount }, (_, index) => (
                      <span key={index + 1}>{index + 1}</span>
                    ))}
                  </div>
                  <pre>
                    <code>{activeFeature.code}</code>
                  </pre>
                </div>
              </div>
              <div className="dev-dx-preview-status">
                <span>{activeFeature.lang}</span>
                <span>UTF-8</span>
                <span>Ln {lineCount}, Col 1</span>
              </div>
            </div>
            <div className="dev-dx-preview-glow" />
          </div>
        </div>
      </div>
    </section>
  )
}
