// pages/Home/sections/Features/Content/index.vue
<template>
  <NucFeatureTemplate
    section-id="content-management"
    :badge="$t('features-content-badge')"
    :heading-prefix="$t('features-content-heading-prefix')"
    :heading-highlight="$t('features-content-heading-highlight')"
    :description="$t('features-content-description')"
    :features="features"
    visual-position="left"
  >
    <div class="content-preview">
      <div class="preview-header">
        <div class="preview-dot"></div>
        <div class="preview-dot"></div>
        <div class="preview-dot"></div>
      </div>
      <div class="preview-body">
        <div class="preview-sidebar">
          <div class="sidebar-item active">
            <Icon name="mdi:file-document-outline" />
          </div>
          <div class="sidebar-item"><Icon name="mdi:image-outline" /></div>
          <div class="sidebar-item"><Icon name="mdi:cog-outline" /></div>
        </div>
        <div class="preview-content">
          <div class="content-block title"></div>
          <div class="content-block text"></div>
          <div class="content-block text short"></div>
          <div class="content-block image"></div>
        </div>
      </div>
    </div>
  </NucFeatureTemplate>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

import type { FeatureItemInterface } from '../Template'
import { NucFeatureTemplate } from '../Template'

const { t } = useI18n()

const features: FeatureItemInterface[] = [
  { icon: 'mdi:pencil-outline', label: t('features-content-feat-edit') },
  { icon: 'mdi:image-plus-outline', label: t('features-content-feat-images') },
  {
    icon: 'mdi:rocket-launch-outline',
    label: t('features-content-feat-publish'),
  },
]
</script>

// pages/home/sections/features/content/index.tsx
'use client'

import type { JSX } from 'react'

import type { FeatureItemInterface } from 'nucleify'
import { AdIcon, NucFeatureTemplate, t } from 'nucleify'

import './_index.scss'

export function NucContent(): JSX.Element {
  const features: FeatureItemInterface[] = [
    { icon: 'mdi:pencil-outline', label: t('features-content-feat-edit') },
    {
      icon: 'mdi:image-plus-outline',
      label: t('features-content-feat-images'),
    },
    {
      icon: 'mdi:rocket-launch-outline',
      label: t('features-content-feat-publish'),
    },
  ]

  return (
    <NucFeatureTemplate
      sectionId="content-management"
      badge={t('features-content-badge')}
      headingPrefix={t('features-content-heading-prefix')}
      headingHighlight={t('features-content-heading-highlight')}
      description={t('features-content-description')}
      features={features}
      visualPosition="left"
    >
      <div className="content-preview">
        <div className="preview-header">
          <div className="preview-dot" />
          <div className="preview-dot" />
          <div className="preview-dot" />
        </div>
        <div className="preview-body">
          <div className="preview-sidebar">
            <div className="sidebar-item active">
              <AdIcon icon="mdi:file-document-outline" />
            </div>
            <div className="sidebar-item">
              <AdIcon icon="mdi:image-outline" />
            </div>
            <div className="sidebar-item">
              <AdIcon icon="mdi:cog-outline" />
            </div>
          </div>
          <div className="preview-content">
            <div className="content-block title" />
            <div className="content-block text" />
            <div className="content-block text short" />
            <div className="content-block image" />
          </div>
        </div>
      </div>
    </NucFeatureTemplate>
  )
}
