// pages/services/business-websites/index.vue
<template>
  <div class="service-container">
    <section class="service-hero">
      <div class="service-hero-decoration service-hero-decoration-1">
        <Icon name="mdi:hexagon-outline" />
      </div>
      <div class="service-hero-decoration service-hero-decoration-2">
        <Icon name="mdi:triangle-outline" />
      </div>

      <div class="service-hero-content container">
        <nuc-shiny-badge icon="mdi:domain" :label="$t('service-bw-badge')" />

        <h1 class="service-hero-title">
          {{ $t('service-bw-title') }}
          <span class="service-hero-title-highlight">
            {{ $t('service-bw-title-highlight') }}
          </span>
        </h1>

        <p class="service-hero-subtitle">{{ $t('service-bw-subtitle') }}</p>

        <nuc-trust-badges :items="trustItems" />
      </div>
    </section>

    <section class="service-features">
      <div class="container">
        <div class="service-features-grid">
          <div
            v-for="feature in features"
            :key="feature.title"
            class="service-feature-card"
          >
            <div class="service-feature-card-icon">
              <Icon :name="feature.icon" />
            </div>
            <h3>{{ feature.title }}</h3>
            <p>{{ feature.desc }}</p>
          </div>
        </div>
      </div>
    </section>

    <section class="service-scope">
      <div class="container">
        <div class="service-scope-layout">
          <div class="service-scope-info">
            <nuc-shiny-badge
              icon="mdi:clipboard-check-outline"
              :label="$t('service-bw-scope-badge')"
            />
            <h2 class="service-section-heading service-section-heading-left">
              {{ $t('service-bw-scope-heading') }}
              <span class="highlight">
                {{ $t('service-bw-scope-highlight') }}
              </span>
            </h2>
            <p class="service-scope-desc">{{ $t('service-bw-scope-desc') }}</p>
          </div>
          <div class="service-scope-checklist">
            <div
              v-for="(item, i) in scopeItems"
              :key="item"
              class="service-scope-item"
              :style="{ animationDelay: `${i * 0.08}s` }"
            >
              <div class="service-scope-check">
                <Icon name="mdi:check-bold" />
              </div>
              <span>{{ item }}</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="service-process-mini">
      <div class="container">
        <h2 class="service-section-heading">
          {{ $t('service-bw-process-heading') }}
          <span class="highlight">
            {{ $t('service-bw-process-highlight') }}
          </span>
        </h2>

        <div class="service-process-steps">
          <div
            v-for="(step, i) in processSteps"
            :key="step.title"
            class="service-process-step"
          >
            <div class="service-process-step-num">
              {{ String(i + 1).padStart(2, '0') }}
            </div>
            <div class="service-process-step-icon">
              <Icon :name="step.icon" />
            </div>
            <h3>{{ step.title }}</h3>
            <p>{{ step.desc }}</p>
            <div
              v-if="i < processSteps.length - 1"
              class="service-process-step-connector"
            >
              <Icon name="mdi:chevron-right" />
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="service-benefits">
      <div class="container">
        <h2 class="service-section-heading">
          {{ $t('service-bw-benefits-heading') }}
          <span class="highlight">
            {{ $t('service-bw-benefits-highlight') }}
          </span>
        </h2>

        <div class="service-benefits-grid">
          <div
            v-for="benefit in benefits"
            :key="benefit.title"
            class="service-benefit-item"
          >
            <div class="service-benefit-icon">
              <Icon :name="benefit.icon" />
            </div>
            <div class="service-benefit-content">
              <span>{{ benefit.title }}</span>
              <p>{{ benefit.desc }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <LazyNucSectionFaq site="home" />
    <LazyNucSectionContact />
  </div>
</template>

<script setup lang="ts">
import { defineAsyncComponent } from 'vue'
import { useI18n } from 'vue-i18n'

import type { NucTrustBadgeItemInterface } from 'nucleify'

const { t } = useI18n()

const trustItems: NucTrustBadgeItemInterface[] = [
  { icon: 'mdi:responsive', label: t('service-bw-trust-responsive') },
  { icon: 'mdi:magnify', label: t('service-bw-trust-seo') },
  { icon: 'mdi:headset', label: t('service-bw-trust-support') },
]

const features = [
  {
    icon: 'mdi:palette-outline',
    title: t('service-bw-feat-design-title'),
    desc: t('service-bw-feat-design-desc'),
  },
  {
    icon: 'mdi:pencil-ruler',
    title: t('service-bw-feat-cms-title'),
    desc: t('service-bw-feat-cms-desc'),
  },
  {
    icon: 'mdi:chart-line',
    title: t('service-bw-feat-analytics-title'),
    desc: t('service-bw-feat-analytics-desc'),
  },
  {
    icon: 'mdi:cellphone-link',
    title: t('service-bw-feat-responsive-title'),
    desc: t('service-bw-feat-responsive-desc'),
  },
  {
    icon: 'mdi:shield-lock-outline',
    title: t('service-bw-feat-security-title'),
    desc: t('service-bw-feat-security-desc'),
  },
  {
    icon: 'mdi:rocket-launch-outline',
    title: t('service-bw-feat-speed-title'),
    desc: t('service-bw-feat-speed-desc'),
  },
]

const scopeItems = [
  t('service-bw-scope-1'),
  t('service-bw-scope-2'),
  t('service-bw-scope-3'),
  t('service-bw-scope-4'),
  t('service-bw-scope-5'),
  t('service-bw-scope-6'),
  t('service-bw-scope-7'),
  t('service-bw-scope-8'),
]

const processSteps = [
  {
    icon: 'mdi:chat-outline',
    title: t('service-bw-step-1-title'),
    desc: t('service-bw-step-1-desc'),
  },
  {
    icon: 'mdi:pencil-ruler',
    title: t('service-bw-step-2-title'),
    desc: t('service-bw-step-2-desc'),
  },
  {
    icon: 'mdi:code-tags',
    title: t('service-bw-step-3-title'),
    desc: t('service-bw-step-3-desc'),
  },
  {
    icon: 'mdi:rocket-launch-outline',
    title: t('service-bw-step-4-title'),
    desc: t('service-bw-step-4-desc'),
  },
]

const benefits = [
  {
    icon: 'mdi:trophy-outline',
    title: t('service-bw-benefit-credibility-title'),
    desc: t('service-bw-benefit-credibility-desc'),
  },
  {
    icon: 'mdi:account-group-outline',
    title: t('service-bw-benefit-customers-title'),
    desc: t('service-bw-benefit-customers-desc'),
  },
  {
    icon: 'mdi:trending-up',
    title: t('service-bw-benefit-growth-title'),
    desc: t('service-bw-benefit-growth-desc'),
  },
]

const LazyNucSectionFaq = defineAsyncComponent(
  () => import('../../../../nuc_sections/faq/index.vue')
)
const LazyNucSectionContact = defineAsyncComponent(
  () => import('../../../../nuc_sections/contact/index.vue')
)
</script>

<style lang="scss">
@import '../index';
</style>

// pages/services/business-websites/index.tsx
'use client'

import type { JSX } from 'react'

import {
  AdIcon,
  NucSectionContact,
  NucSectionFaq,
  NucShinyBadge,
  NucTrustBadges,
  t,
} from 'nucleify'

import '../_index.scss'

export function NucBusinessWebsitesPage(): JSX.Element {
  const trustItems = [
    { icon: 'mdi:responsive', label: t('service-bw-trust-responsive') },
    { icon: 'mdi:magnify', label: t('service-bw-trust-seo') },
    { icon: 'mdi:headset', label: t('service-bw-trust-support') },
  ]

  const features = [
    {
      icon: 'mdi:palette-outline',
      title: t('service-bw-feat-design-title'),
      desc: t('service-bw-feat-design-desc'),
    },
    {
      icon: 'mdi:pencil-ruler',
      title: t('service-bw-feat-cms-title'),
      desc: t('service-bw-feat-cms-desc'),
    },
    {
      icon: 'mdi:chart-line',
      title: t('service-bw-feat-analytics-title'),
      desc: t('service-bw-feat-analytics-desc'),
    },
    {
      icon: 'mdi:cellphone-check',
      title: t('service-bw-feat-responsive-title'),
      desc: t('service-bw-feat-responsive-desc'),
    },
    {
      icon: 'mdi:shield-lock-outline',
      title: t('service-bw-feat-security-title'),
      desc: t('service-bw-feat-security-desc'),
    },
    {
      icon: 'mdi:rocket-outline',
      title: t('service-bw-feat-speed-title'),
      desc: t('service-bw-feat-speed-desc'),
    },
  ]

  const benefits = [
    {
      icon: 'mdi:shield-check-outline',
      title: t('service-bw-benefit-credibility-title'),
      desc: t('service-bw-benefit-credibility-desc'),
    },
    {
      icon: 'mdi:account-search-outline',
      title: t('service-bw-benefit-customers-title'),
      desc: t('service-bw-benefit-customers-desc'),
    },
    {
      icon: 'mdi:trending-up',
      title: t('service-bw-benefit-growth-title'),
      desc: t('service-bw-benefit-growth-desc'),
    },
  ]

  const scopeItems = [
    t('service-bw-scope-1'),
    t('service-bw-scope-2'),
    t('service-bw-scope-3'),
    t('service-bw-scope-4'),
    t('service-bw-scope-5'),
    t('service-bw-scope-6'),
    t('service-bw-scope-7'),
    t('service-bw-scope-8'),
  ]

  const processSteps = [
    {
      num: '01',
      icon: 'mdi:chat-outline',
      title: t('service-bw-step-1-title'),
      desc: t('service-bw-step-1-desc'),
    },
    {
      num: '02',
      icon: 'mdi:vector-square',
      title: t('service-bw-step-2-title'),
      desc: t('service-bw-step-2-desc'),
    },
    {
      num: '03',
      icon: 'mdi:code-tags',
      title: t('service-bw-step-3-title'),
      desc: t('service-bw-step-3-desc'),
    },
    {
      num: '04',
      icon: 'mdi:rocket-launch-outline',
      title: t('service-bw-step-4-title'),
      desc: t('service-bw-step-4-desc'),
    },
  ]

  return (
    <div className="service-container">
      <section className="service-hero">
        <div className="service-hero-decoration service-hero-decoration-1">
          <AdIcon icon="mdi:hexagon-outline" />
        </div>
        <div className="service-hero-decoration service-hero-decoration-2">
          <AdIcon icon="mdi:triangle-outline" />
        </div>

        <div className="service-hero-content container">
          <NucShinyBadge icon="mdi:domain" label={t('service-bw-badge')} />
          <h1 className="service-hero-title">
            {t('service-bw-title')}
            <span className="service-hero-title-highlight">
              {t('service-bw-title-highlight')}
            </span>
          </h1>
          <p className="service-hero-subtitle">{t('service-bw-subtitle')}</p>
          <NucTrustBadges items={trustItems} />
        </div>
      </section>

      <section className="service-features">
        <div className="container">
          <div className="service-features-grid">
            {features.map((feature) => (
              <div key={feature.title} className="service-feature-card">
                <div className="service-feature-card-icon">
                  <AdIcon icon={feature.icon} />
                </div>
                <h3>{feature.title}</h3>
                <p>{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="service-scope">
        <div className="container service-scope-layout">
          <div>
            <NucShinyBadge
              icon="mdi:check-decagram-outline"
              label={t('service-bw-scope-badge')}
            />
            <h2 className="service-section-heading service-section-heading-left">
              {t('service-bw-scope-heading')}
              <span className="highlight">
                {t('service-bw-scope-highlight')}
              </span>
            </h2>
            <p className="service-scope-desc">{t('service-bw-scope-desc')}</p>
          </div>
          <div className="service-scope-checklist">
            {scopeItems.map((item) => (
              <div key={item} className="service-scope-item">
                <div className="service-scope-check">
                  <AdIcon icon="mdi:check-bold" />
                </div>
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="service-process-mini">
        <div className="container">
          <h2 className="service-section-heading">
            {t('service-bw-process-heading')}
            <span className="highlight">
              {t('service-bw-process-highlight')}
            </span>
          </h2>
          <div className="service-process-steps">
            {processSteps.map((step, index) => (
              <div key={step.title} className="service-process-step">
                <div className="service-process-step-num">{step.num}</div>
                <div className="service-process-step-icon">
                  <AdIcon icon={step.icon} />
                </div>
                <h3>{step.title}</h3>
                <p>{step.desc}</p>
                {index < processSteps.length - 1 && (
                  <div className="service-process-step-connector">
                    <AdIcon icon="mdi:chevron-right" />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="service-benefits">
        <div className="container">
          <h2 className="service-section-heading">
            {t('service-bw-benefits-heading')}
            <span className="highlight">
              {t('service-bw-benefits-highlight')}
            </span>
          </h2>
          <div className="service-benefits-grid">
            {benefits.map((benefit) => (
              <div key={benefit.title} className="service-benefit-item">
                <div className="service-benefit-icon">
                  <AdIcon icon={benefit.icon} />
                </div>
                <div className="service-benefit-content">
                  <span>{benefit.title}</span>
                  <p>{benefit.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <NucSectionFaq site="home" />
      <NucSectionContact />
    </div>
  )
}
