// pages/home/sections/features/template/index.tsx
'use client'

import type { JSX, ReactNode } from 'react'

import type { FeatureTemplateInterface } from 'nucleify'
import { AdCard, AdIcon } from 'nucleify'

import './_index.scss'

interface Props extends FeatureTemplateInterface {
  children: ReactNode
}

export function NucFeatureTemplate({
  sectionId,
  badge,
  headingPrefix,
  headingHighlight,
  description,
  features,
  visualPosition = 'right',
  children,
}: Props): JSX.Element {
  const sectionClassName =
    visualPosition === 'left'
      ? 'feature-section visual-left'
      : 'feature-section'

  return (
    <section id={sectionId} className={sectionClassName}>
      <div className="feature-container container">
        <div className="feature-info">
          <span className="feature-badge">{badge}</span>
          <h2 className="feature-heading">
            {headingPrefix}
            <span className="highlight"> {headingHighlight}</span>
          </h2>
          <p className="feature-description">{description}</p>
          <div className="feature-list">
            {features.map((feature) => (
              <div key={feature.label} className="feature-item">
                <AdIcon icon={feature.icon} />
                <span>{feature.label}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="feature-visual">
          <AdCard className="nuc-card-base feature-card">{children}</AdCard>
        </div>
      </div>
    </section>
  )
}

// pages/Home/sections/Features/Template/index.vue
<template>
  <section
    :id="props.sectionId"
    :class="['feature-section', { 'visual-left': props.visualPosition === 'left' }]"
  >
    <div class="feature-container container">
      <div class="feature-info">
        <span class="feature-badge">{{ props.badge }}</span>
        <h2 class="feature-heading">
          {{ props.headingPrefix }}
          <span class="highlight">{{ props.headingHighlight }}</span>
        </h2>
        <p class="feature-description">{{ props.description }}</p>

        <div class="feature-list">
          <div
            v-for="feature in props.features"
            :key="feature.label"
            class="feature-item"
          >
            <Icon :name="feature.icon" />
            <span>{{ feature.label }}</span>
          </div>
        </div>
      </div>

      <div class="feature-visual">
        <ad-card class="nuc-card-base feature-card">
          <template #content> <slot /> </template>
        </ad-card>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import type { FeatureTemplateInterface } from './interfaces'

const props = withDefaults(defineProps<FeatureTemplateInterface>(), {
  visualPosition: 'right',
})
</script>
