// pages/home/sections/core/index.tsx
'use client'

import { type CSSProperties, useEffect, useMemo, useState } from 'react'

import { NUC_HOME_COPY, NUC_HOME_CRAFT_SAMPLES } from '../../constants/content'

import './_index.scss'

const copy = NUC_HOME_COPY
const samples = NUC_HOME_CRAFT_SAMPLES

export function NucHomeCore() {
  const [activeIndex, setActiveIndex] = useState(0)
  const [paused, setPaused] = useState(false)
  const [hovering, setHovering] = useState(false)
  const [wiping, setWiping] = useState(true)
  const [wipeKey, setWipeKey] = useState(0)

  const active = useMemo(
    () => samples[activeIndex] ?? samples[0]!,
    [activeIndex]
  )

  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
    if (paused || hovering) return

    const timer = window.setInterval(() => {
      setActiveIndex((index) => (index + 1) % samples.length)
    }, 3800)

    return () => window.clearInterval(timer)
  }, [paused, hovering])

  useEffect(() => {
    setWiping(false)
    const id = window.requestAnimationFrame(() => {
      setWipeKey((key) => key + 1)
      setWiping(true)
    })
    return () => window.cancelAnimationFrame(id)
  }, [activeIndex])

  function select(index: number, lock = false): void {
    setActiveIndex(index)
    if (lock) setPaused(true)
  }

  return (
    <section
      id="core"
      className="nuc-home-section nuc-home-core nuc-home-panel"
      aria-labelledby="nuc-home-core-title"
      style={{ '--core-accent': active.accent } as CSSProperties}
    >
      <div className="nuc-home-core-head">
        <p className="nuc-home-eyebrow">{copy.coreEyebrow}</p>
        <h2 id="nuc-home-core-title" className="nuc-home-title">
          {copy.coreTitle}
        </h2>
        <p className="nuc-home-support">{copy.coreSupport}</p>
      </div>

      <div
        className="nuc-home-core-stage"
        onMouseEnter={() => setHovering(true)}
        onMouseLeave={() => setHovering(false)}
      >
        <div
          key={wipeKey}
          className={`nuc-home-core-canvas${wiping ? ' is-wiping' : ''}`}
        >
          <div className="nuc-home-core-aura" aria-hidden="true" />
          <div className="nuc-home-core-orbit" aria-hidden="true" />

          <div className="nuc-home-core-portal" aria-hidden="true">
            <div
              className={`nuc-home-core-layer nuc-home-core-layer-shipped nuc-home-core-layer-${active.id}`}
            >
              <div className="nuc-home-core-chrome">
                <i />
                <i />
                <i />
                <em>{copy.coreShippedLabel}</em>
              </div>
              <div className="nuc-home-core-screen">
                <div className="nuc-home-core-preview-top" />
                <div className="nuc-home-core-preview-body">
                  <span />
                  <span />
                  <span />
                </div>
                <div className="nuc-home-core-swatches">
                  <b />
                  <b />
                  <b />
                  <b />
                </div>
              </div>
            </div>

            <div
              className={`nuc-home-core-layer nuc-home-core-layer-yours nuc-home-core-layer-${active.id}`}
            >
              <div className="nuc-home-core-chrome">
                <i />
                <i />
                <i />
                <em>{copy.coreYoursLabel}</em>
              </div>
              <div className="nuc-home-core-screen">
                <div className="nuc-home-core-preview-top" />
                <div className="nuc-home-core-preview-body">
                  <span />
                  <span />
                  <span />
                </div>
                <div className="nuc-home-core-swatches">
                  <b />
                  <b />
                  <b />
                  <b />
                </div>
              </div>
            </div>

            <div className="nuc-home-core-blade">
              <span className="nuc-home-core-blade-glow" />
              <span className="nuc-home-core-blade-edge" />
              <span className="nuc-home-core-blade-tag">override</span>
            </div>
          </div>

          <aside className="nuc-home-core-legend" aria-live="polite">
            <div className="nuc-home-core-rail-item nuc-home-core-rail-item-shipped">
              <span className="nuc-home-core-diff nuc-home-core-diff-minus">
                −
              </span>
              <div>
                <p className="nuc-home-core-rail-kicker">
                  {copy.coreShippedLabel}
                </p>
                <p className="nuc-home-core-rail-path">{active.shippedPath}</p>
                <p className="nuc-home-core-rail-note">{active.shippedNote}</p>
              </div>
            </div>
            <div className="nuc-home-core-rail-item nuc-home-core-rail-item-yours">
              <span className="nuc-home-core-diff nuc-home-core-diff-plus">
                +
              </span>
              <div>
                <p className="nuc-home-core-rail-kicker">
                  {copy.coreYoursLabel}
                </p>
                <p className="nuc-home-core-rail-path">{active.yoursPath}</p>
                <p className="nuc-home-core-rail-note">{active.yoursNote}</p>
              </div>
            </div>
            <p className="nuc-home-core-keep">
              <nui-icon icon="mdi:shield-check-outline" />
              {copy.coreKeepLabel}
            </p>
          </aside>
        </div>

        <div
          className="nuc-home-core-kinds"
          role="tablist"
          aria-label="Override kinds"
        >
          {samples.map((sample, index) => (
            <button
              key={sample.id}
              type="button"
              role="tab"
              className={`nuc-home-core-kind${index === activeIndex ? ' is-active' : ''}`}
              aria-selected={index === activeIndex}
              onMouseEnter={() => select(index, false)}
              onFocus={() => select(index, false)}
              onClick={() => select(index, true)}
            >
              <nui-icon icon={sample.icon} />
              <span>{sample.kind}</span>
            </button>
          ))}
        </div>
      </div>
    </section>
  )
}

// pages/home/sections/core/index.vue
<template>
  <section
    id="core"
    class="nuc-home-section nuc-home-core nuc-home-panel"
    aria-labelledby="nuc-home-core-title"
    :style="stageStyle"
  >
    <div class="nuc-home-core-head">
      <p class="nuc-home-eyebrow">{{ copy.coreEyebrow }}</p>
      <h2 id="nuc-home-core-title" class="nuc-home-title">
        {{ copy.coreTitle }}
      </h2>
      <p class="nuc-home-support">{{ copy.coreSupport }}</p>
    </div>

    <div
      class="nuc-home-core-stage"
      @mouseenter="hovering = true"
      @mouseleave="hovering = false"
    >
      <div class="nuc-home-core-canvas" :class="{ 'is-wiping': wiping }">
        <div class="nuc-home-core-aura" aria-hidden="true" />
        <div class="nuc-home-core-orbit" aria-hidden="true" />

        <div class="nuc-home-core-portal" aria-hidden="true">
          <div
            class="nuc-home-core-layer nuc-home-core-layer-shipped"
            :class="`nuc-home-core-layer-${active.id}`"
          >
            <div class="nuc-home-core-chrome">
              <i /><i /><i />
              <em>{{ copy.coreShippedLabel }}</em>
            </div>
            <div class="nuc-home-core-screen">
              <div class="nuc-home-core-preview-top" />
              <div class="nuc-home-core-preview-body">
                <span /><span /><span />
              </div>
              <div class="nuc-home-core-swatches">
                <b /><b /><b /><b />
              </div>
            </div>
          </div>

          <div
            class="nuc-home-core-layer nuc-home-core-layer-yours"
            :class="`nuc-home-core-layer-${active.id}`"
          >
            <div class="nuc-home-core-chrome">
              <i /><i /><i />
              <em>{{ copy.coreYoursLabel }}</em>
            </div>
            <div class="nuc-home-core-screen">
              <div class="nuc-home-core-preview-top" />
              <div class="nuc-home-core-preview-body">
                <span /><span /><span />
              </div>
              <div class="nuc-home-core-swatches">
                <b /><b /><b /><b />
              </div>
            </div>
          </div>

          <div class="nuc-home-core-blade">
            <span class="nuc-home-core-blade-glow" />
            <span class="nuc-home-core-blade-edge" />
            <span class="nuc-home-core-blade-tag">override</span>
          </div>
        </div>

        <aside class="nuc-home-core-legend" aria-live="polite">
          <div class="nuc-home-core-rail-item nuc-home-core-rail-item-shipped">
            <span class="nuc-home-core-diff nuc-home-core-diff-minus">−</span>
            <div>
              <p class="nuc-home-core-rail-kicker">
                {{ copy.coreShippedLabel }}
              </p>
              <p class="nuc-home-core-rail-path">{{ active.shippedPath }}</p>
              <p class="nuc-home-core-rail-note">{{ active.shippedNote }}</p>
            </div>
          </div>
          <div class="nuc-home-core-rail-item nuc-home-core-rail-item-yours">
            <span class="nuc-home-core-diff nuc-home-core-diff-plus">+</span>
            <div>
              <p class="nuc-home-core-rail-kicker">
                {{ copy.coreYoursLabel }}
              </p>
              <p class="nuc-home-core-rail-path">{{ active.yoursPath }}</p>
              <p class="nuc-home-core-rail-note">{{ active.yoursNote }}</p>
            </div>
          </div>
          <p class="nuc-home-core-keep">
            <nui-icon icon="mdi:shield-check-outline" />
            {{ copy.coreKeepLabel }}
          </p>
        </aside>
      </div>

      <div
        class="nuc-home-core-kinds"
        role="tablist"
        aria-label="Override kinds"
      >
        <button
          v-for="(sample, index) in samples"
          :key="sample.id"
          type="button"
          role="tab"
          class="nuc-home-core-kind"
          :class="{ 'is-active': index === activeIndex }"
          :aria-selected="index === activeIndex"
          @mouseenter="select(index, false)"
          @focus="select(index, false)"
          @click="select(index, true)"
        >
          <nui-icon :icon="sample.icon" />
          <span>{{ sample.kind }}</span>
        </button>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
  type CSSProperties,
} from 'vue'

import { NUC_HOME_COPY, NUC_HOME_CRAFT_SAMPLES } from '../../constants/content'

const copy = NUC_HOME_COPY
const samples = NUC_HOME_CRAFT_SAMPLES

const activeIndex = ref(0)
const paused = ref(false)
const hovering = ref(false)
const wiping = ref(true)

const active = computed(() => samples[activeIndex.value] ?? samples[0]!)

const stageStyle = computed(
  () =>
    ({
      '--core-accent': active.value.accent,
    }) as CSSProperties
)

let timer: number | undefined

async function replayWipe(): Promise<void> {
  wiping.value = false
  await nextTick()
  requestAnimationFrame(() => {
    wiping.value = true
  })
}

function select(index: number, lock = false): void {
  activeIndex.value = index
  if (lock) paused.value = true
}

function tick(): void {
  if (paused.value || hovering.value) return
  activeIndex.value = (activeIndex.value + 1) % samples.length
}

watch(activeIndex, () => {
  void replayWipe()
})

onMounted(() => {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    wiping.value = true
    return
  }
  timer = window.setInterval(tick, 3800)
})

onBeforeUnmount(() => {
  if (timer) window.clearInterval(timer)
})
</script>

<style lang="scss" scoped>
@import 'index';
</style>
